#!/bin/sh

if [ -z "$*" ]; then 
	echo "No args, Syntax: newfile <file name>"; 
else
	FILE=$1
	
	if [ ! -f $FILE ]; then
		echo "Creating new shell:" $1
		cat >~/$1 <<EOF
#!/bin/sh

EOF
		if [ -z "$2" ]; then
			echo "k"
		else
			chmod 777 $1
		fi
	else
		echo $1 "aleady exists"
	fi
fi


