#!/bin/sh

if [ -z "$*" ]; then 
	echo "No args, Syntax: web <arg1> <arg2>"; 
else	
	if [ "$1" = "ip" ]; then
		hostname -I
	elif [ "$1" = "flask" ]; then
		if [ "$2" = "start" ]; then
			sudo systemctl start flask.service
		elif [ "$2" = "stop" ]; then
			sudo systemctl stop flask.service
		elif [ "$2" = "restart" ]; then
			sudo systemctl restart flask.service
		elif [ "$2" = "status" ]; then
			sudo systemctl status flask.service
		else
			echo "Incorrect Arg - Correct Args: start, stop, restart, status"
		fi
	elif [ "$1" = "noip" ]; then
		sudo /usr/local/bin/noip2 -S
	else
		echo "Incorrect Arg - Correct Args: ip, flask, noip"
	fi
fi

